#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -l vmem=30gb
#PBS -N pynet

# This file is used to execute PyNets on brainlife.
# brainlife stages this git repo, writes `config.json` and execute this script.
# this script reads the `config.json` and execute pynets container through singularity

set -x
set -e

echo "running pynet"
mkdir -p output tmp
singularity run -e docker://dpys/pynets:latest output \
    -p 1 -mod 'partcorr' 'corr' -min_thr 0.20 -max_thr 1.00 -step_thr 0.10 -sm 0 2 4 -hp 0 0.028 0.080
    -ct 'ward' -k 100 200 -cm '/outputs/triple_net_ICA_overlap_3_sig_bin.nii.gz' \
    -norm 6 \
    -anat $(jq .anat config.json) \
    -func $(jq .bold config.json) \
    -conf $(jq .regressor config.json) \
    -m $(jq .brainmask config.json) \
    -id 'PARTICIPANT_SESSION' -plug 'MultiProc' -work 'tmp' -pm '24,48'

